
version: '3.9'

services:
  web:
    build: config
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:15.1
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"